# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98a0a01ec85bf3e70d0d8173d76a6b545d4fe6eb42bdb9cf058c9f85b4c08a0bda4f3cf88113f09bbf25b64492cf1371bbac79879e080edd75f63d904ca3dfc4

test:
  secret_key_base: 5ad2b45b3ba1f2f421a82bb421b7d0b0774a77bb395468e92cafdd79c50260ebad935d32b58b54b2245eb537fec0b74b69b1804cf63818d01e176ab73414aead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
